[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/meet"
  to = "https://calendar.app.google/sv3Sb5sjUxxTdssv8"
  status = 301
  force = true  # Ensures the redirect always happens, even if there is content in the path

[[redirects]]
  from = "/opportunities"
  to = "https://docs.google.com/document/d/1TRfgYpy8dOTXU_KJpqq1ZkBIUKqpyOaW6vBqufpRqGw/edit"
  status = 301
  force = true  # Ensures the redirect always happens, even if there is content in the path

  [[redirects]]
  from = "/eoi"
  to = "https://forms.gle/6BEMc3DYuU52yfGn8"
  status = 301
  force = true  # Ensures the redirect always happens, even if there is content in the path

  [[redirects]]
  from = "/intro"
  to = "https://docs.google.com/document/d/1UjL4NztBiiTYw7p-HZrefE2XocCSKZ77WEOQ-P3LoH0/copy"
  status = 301
  force = true  # Ensures the redirect always happens, even if there is content in the path
  
  [[redirects]]
  from = "/cv"
  to = "https://docs.google.com/document/d/1h9amaSB6MOZ1lSANBEhf1SOaMfQg4Y2_12wK3l-CrT4/edit"
  status = 301
  force = true  # Ensures the redirect always happens, even if there is content in the path

  
